version: "3.8"

services:
  backend:
    build: ./backend
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 # Default from Dockerfile is fine
    volumes:
      - ./data:/data
    ports:
      - "22001:8000"
    environment:
      - DATABASE_URL=sqlite:////data/tidal_helper.db

  frontend:
    build: ./frontend
    ports:
      - "22002:80"
    depends_on:
      - backend
